(require 'cl)
(defun bind-func (key func)
  (global-set-key (read-kbd-macro key) func))
(show-paren-mode t)
(setq show-paren-delay 0)
(setq show-paren-style 'expression)
(set-face-background 'show-paren-match-face "#533")
(setq-default show-trailing-whitespace t)
(line-number-mode t)
(column-number-mode t)
(global-linum-mode t)
(setq linum-format "%4d ")
(bind-func "C-x g" 'goto-line)
(cua-mode t)
(setq cua-enable-cua-keys nil)
(global-set-key (kbd "C-x RET RET") 'cua-rectangle-mark-mode)
(setq inhibit-startup-screen t)
(setq initial-scratch-message "")
(require 'tramp-cmds)
(require 'package)
(package-initialize)

(require 'powerline)
(powerline-center-theme)

(recentf-mode t)
(setq recentf-max-menu-items 10)
(setq recentf-max-saved-items 3000)
(setq visible-bell t)
(setq ring-bell-function 'ignore)
(require 'misc)
(global-set-key "\M-f" 'forward-to-word)
(require 'magit)
(require 'undo-tree)
(global-undo-tree-mode 1)
(global-set-key (kbd "M-/") 'undo-tree-redo)
(require 'helm)
(global-set-key (kbd "C-x f") 'helm-for-files)
(require 'helm-config)
(helm-mode 1)
(require 'helm-ag)
(setq helm-ag-base-command "ag --nocolor --nogrou")
(global-set-key (kbd "C-c s") 'helm-ag-buffers)
(require 'auto-complete)
(add-hook 'before-save-hook 'delete-trailing-whitespace)
(define-key ac-complete-mode-map "\C-n" 'ac-next)
(define-key ac-complete-mode-map "\C-p" 'ac-previous)
(setq ac-delay 0.1)
(setq ac-use-fuzzy t)
(setq ac-use-comphist t)
(setq ac-auto-show-menu 0.1)
(setq ac-quick-help-delay 0.1)

(define-key helm-read-file-map (kbd "TAB") 'helm-execute-persistent-action)
(define-key helm-find-files-map (kbd "TAB") 'helm-execute-persistent-action)
(global-set-key (kbd "M-x") 'helm-M-x)
(setq make-backup-files nil)


(setq scroll-conservatively 0)
(setq scroll-margin 0)
(setq scroll-step 1)
(setq comint-scroll-show-maximum-output t)


(tool-bar-mode 0)
(menu-bar-mode 0)
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")

(defun my-ac-config ()
  (setq-default ac-sources '(ac-source-abbrev ac-source-dictionary ac-source-words-in-same-mode-buffers))
  (global-auto-complete-mode t))
(my-ac-config)
(add-to-list 'auto-mode-alist '("\\.cl\\'" . c-mode))
(add-to-list 'auto-mode-alist '("\\.fragmentshader\\'" . c-mode))
(add-to-list 'auto-mode-alist '("\\.vertexshader\\'" . c-mode))
(c-set-offset 'arglist-intro 2)
(c-set-offset 'arglist-close 0)
(load-theme 'wombat t)
